### ISSUE TITLE
install tailscale as service to ssh into machine remotely

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/rctv#21]

**Comment by gregsadetsky** [comment]
The other thing you'll want to do is add a "tag" for the Pi in Tailscale's admin interface. Normally, Tailscale expires your keys every once in a while, and you have to re-authenticate. When you add a tag to a computer, Tailscale assumes that computer is "infrastructure" rather than a personal device, and disables key expiry by default. More info here: https://tailscale.com/kb/1085/auth-keys/

**Comment by gregsadetsky** [comment]
@jryio could you please add a ""tag"" to the raspi on tailscale? so that we don't have to re-auth to tailscale on the raspi?

per [Daniel's comment](https://recurse.zulipchat.com/#narrow/stream/398504-397-Bridge/topic/remote.20ssh/near/401414659) and yes --->>> confirmation here!!!!

<img width="798" alt="image" src="https://github.com/gregsadetsky/rctv/assets/1017304/1d3befd3-84ae-4ab6-84bf-c086c170f7f2">

**Comment by gregsadetsky** [comment]
I'm sorry don't do anything thank youuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu 5-steps-ahead-gang hahaha

<img width="274" alt="image" src="https://github.com/gregsadetsky/rctv/assets/1017304/cbbd66e3-6c8a-41af-8136-78fd16dbcc40">

**Comment by jryio** [comment]
@gregsadetsky first thing I did 1️⃣
