### ISSUE TITLE
document database setup

### ISSUE THREAD

**Issue by jryio** [gregsadetsky/rctv#34]
might be good to get some instructions on how to install postgres, create a db, create a user, connect, etc

and also: write a script to either setup DB or connect, or dockerize the thing?

**Comment by gregsadetsky** [comment]
I'm not against it, but I feel like it's low prio in the sense that 1) it's using standard django i.e. it's not "more" work than "just" setting up postgres locally (there's no particular postgres magic) 2) I deploy it to render automatically and they take care of the postgres stuff for us 3) adding docker would make it maybe easier in some ways (more predictable) but it's also more work + adds to the minimal setup. I'm just unsure? 4) in more general terms, I'm not fullly sure that the rctv backend is as interesting to others i.e. I don't really expect people to want to run this / extend this? like... the frontend apps + sdk, hopefully yes but this is more... I don't know

I get though that working on making it more useable/easy to install, etc. might help this project grow/expand from being an RC-only thing or give it more longevity...?

I guess -- what was your reasoning -- did you find the postgres installation confusing or not documented enough, etc.?

thanks!

**Comment by jryio** [comment]
It was that some ppl might not know how to setup postgres running locally 👀, I added a few words. No docker needed.

**Comment by gregsadetsky** [comment]
super, thanks! I use https://postgresapp.com/ it's 1-click and you get a db. we can move the onboarding/how to dev into a separate readme at some point
